spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camplex?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  profiles:
    include: local

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      database: mysql